Ci cd init
samule-i/gneiss-totesys pull request #1
Opened 2023-10-30 15:14 UTC by samule-i

Considerations:
  Should python version be locked to 3.10 to have parity with AWS Lambda?

2023-10-31 12:07 UTC, emanyika approved these changes

2023-10-31 14:15 UTC, jambent requested changes
If it's going to be visible, could my name's spelling be fixed in
data_ingestion/pyproject.toml
?

I'd be happy working with the suggested file system structure, otherwise.

2023-10-31 16:23 UTC, samule-i commented
> If it's going to be visible, could my name's spelling be fixed in data_ingestion/pyproject.toml ?
> 
> I'd be happy working with the suggested file system structure, otherwise.

That's absolutely embarrassing, that'll teach me to proof-read a bit better.
Apologies for that slip-up

2023-10-31 17:00 UTC, RonanTC approved these changes

2023-11-01 09:01 UTC, jambent approved these changes

2023-11-01 09:01 UTC, merged